Zadanie
No1specials/ZadanieStrona pull request #1
Opened 2018-11-02 01:13 UTC by No1specials

2018-11-03 16:12 UTC, purbanski-deftcode requested changes
Posprawdzałem co nie co, zapoznaj się proszę z komentarzami, daj znać jak czegoś nie rozumiesz albo masz pytania no i przede wszystkim popraw co możesz w całym kodzie na podstawie tych komentarzy :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +        <div class="website">
Ogólny komentarz dla całego pliku: staraj się używać wcięć w pliku na 2 spacje zamiast 4.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                <div class="landingText">
Przyjęta konwencja to pisanie klasy w `taki-sposób-oddzielony-myślnikami` zamiast camelCase.
https://medium.freecodecamp.org/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +           <div class="tabela">
Nie używaj polskiego języka w kodzie o ile nie jest to tekst, który musi być po polsku. To samo tyczy się folderów, komentarzy itd.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +        <div class="website">
Staraj się używać jak najmniej divów. Tutaj np. mogłeś dać klasę elementowi `body`. I nadać mu te same style co ma `.website`.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                <div class="landingText">
Tutaj ten dodatkowy div `landingText` jest potrzebny? Widze, że powtarza wszystkie style co `landing` prócz koloru.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <h1 class="mariaLanding dancingFont">MariaAnna</h1>
Co to zasady na stronie powinien być tylko jeden nagłówek `h1`, ten który jest główny :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <h1 class="mariaLanding dancingFont">MariaAnna</h1>
Takie klasy jak `dancingFont` są złą praktyką, sa niesemantyczne
https://maintainablecss.com/chapters/semantics/
Myślę, że odpowiednie style powinieneś po prostu nadać `mariaLanding`. Albo stworzy semantyczną klasę jak `section-heading`. 
Dodatkowo jak masz określoną sekcję strony opatrzoną jakimś nagłówkiem, która stanowi odrębną część tej strony to lepiej jest używać elementu `<section>`

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <a class="seeLanding playFair">See the world through my lens</a>
Jak dajesz znaczniki `a` bez adresu to dodawaj zawsze `href="#"`. Dzieki temu link będzie się zachowywał jak link mimo, że nigdzie nie będzie prowadził.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <div class="bottomLanding"></div>
Starajmy się unikać niepotrzebnych divów. Zamiast tego myślę można użyć pseudo elementy (https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements) a dokładniej tutaj będzie pasował `:after`.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +           <div class="nav">
Zamiast diva z klasą `.nav` lepiej jest użyć element `<nav>`

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                   <li class="bottomWorks">WORKS</li>
To jest nawigacja więc w tych `<li>` powinny jeszcze być linki.
A klasę `bottomWorks` zamieniłbym na `active` :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <a class="loremLanding ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</a>
To chyba nie powinien być link tylko zwykły paragraf :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <a class="seeLanding playFair">See the world through my lens</a>
Dodatkowo to chyba nie powinien być link, zamiast tego linkiem może być główny heading na stronie (albo czasami logo).

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +           <div class="littleText">
Ten div to powinien być `section` oraz lepsza klasa to chyba byłoby po prostu `about-me`. Klasy mają mówić z czym mamy doczynienia.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                <a class="loremText ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wi
To myślę powinien być paragraf. Czemu dałeś link? Coś sugerowało, że ten tekst nim ma być i gdzieś ma prowadzić? :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +           <div class="worksText">
Tutaj ten cały div nie jest raczej potrzebny. Wystarczy po prostu `h2` z odpowiednimi stylami oraz `:after` żeby to podkreślenie zrobić.

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                                <img class="corner1" src="zdj/Corner1.png">
Zamiast tych obrazków można wykorzystać 4 spany które mają border tylko z dwóch stron i za pomocą position absolute umieścić je w odpowiednich rogach tego diva.
Zamiast `tabelaBottom` oczywiście lepiej `:after` wykorzystać.
A do całego tego grida (lepsze określnie btw niż tabela) chyba lepiej wykorzystać grid layout 
https://css-tricks.com/snippets/css/complete-guide-grid/ (jak potrzebujesz dodatkowe materiały to daj znać bo temat na pierwszy rzut oka może wydawać się być skomplikowany)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +               <h2 class="seeLorem ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</h2>
To i tekst niżej to raczej powinny być po prostu paragrafy :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +               <div class="dots">
Animacja dla tych kropek jest trochę chyba za wolna, trochę bym ją przyśpieszył. I dodatkowe punkty jak uda Ci się wyeliminować efekt rozsuwania innych kropek kiedy dana kropka się powiększa :)

2018-11-03 16:12 UTC, purbanski-deftcode commented on index.html
> +                    <a class="sendText ralewayFont">All fields marked with an asterisk (*) are required</a>
Powinien być paragraf zamiast linku.

2018-11-05 23:25 UTC, No1specials commented on index.html
> +        <div class="website">
Poprawione

2018-11-06 00:07 UTC, No1specials commented on index.html
> +                <div class="landingText">
Poprawione

2018-11-06 00:14 UTC, No1specials commented on index.html
> +           <div class="tabela">
Poprawiono

2018-11-06 00:29 UTC, No1specials commented on index.html
> +                    <h1 class="mariaLanding dancingFont">MariaAnna</h1>
Poprawiono

2018-11-06 01:36 UTC, No1specials commented on index.html
> +                    <a class="seeLanding playFair">See the world through my lens</a>
Poprawiono

2018-11-06 02:59 UTC, No1specials commented on index.html
> +                    <div class="bottomLanding"></div>
Poprawiono

2018-11-06 03:04 UTC, No1specials commented on index.html
> +           <div class="nav">
Poprawiono

2018-11-06 03:20 UTC, No1specials commented on index.html
> +                   <li class="bottomWorks">WORKS</li>
Poprawiono

2018-11-06 03:25 UTC, No1specials commented on index.html
> +                    <a class="loremLanding ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</a>
Poprawiono

2018-11-06 03:26 UTC, No1specials commented on index.html
> +                <a class="loremText ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wi
Poprawiono

2018-11-06 23:12 UTC, No1specials commented on index.html
> +               <h2 class="seeLorem ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</h2>
Poprawiono

2018-11-06 23:57 UTC, No1specials commented on index.html
> +                    <a class="sendText ralewayFont">All fields marked with an asterisk (*) are required</a>
Poprawiono

2018-11-07 00:15 UTC, No1specials commented on index.html
> +           <div class="littleText">
Poprawiono

2018-11-07 00:21 UTC, No1specials commented on index.html
> +           <div class="worksText">
Poprawiono

2018-11-07 01:09 UTC, No1specials commented on index.html
> +                                <img class="corner1" src="zdj/Corner1.png">
Poprawione lecz bez grida

2018-11-07 01:12 UTC, No1specials commented on index.html
> +               <h2 class="seeLorem ralewayFont">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.</h2>
Poprawiono, a inne nagłówki też mam zmienić na paragrafy?

2018-11-07 01:12 UTC, No1specials commented on index.html
> +                    <a class="sendText ralewayFont">All fields marked with an asterisk (*) are required</a>
Poprawiono

2018-11-07 01:26 UTC, No1specials commented on index.html
> +               <div class="dots">
Animacja dla kropek została przyśpieszona.  Mimo walki z kropkami mam problem z rozsuwaniem ich

2018-11-07 01:26 UTC, No1specials commented on index.html
> +           <div class="worksText">
Poprawiono

2018-11-09 16:41 UTC, purbanski-deftcode approved these changes
LGTM

2018-11-09 16:41 UTC, merged